name: Run

on:
  schedule:
    # every day at 6:00 am (Beijing time)
    - cron: '0 22 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: go run .
        env:
          CI: 1
          WEATHER_ENDPOINT: ${{ secrets.WEATHER_ENDPOINT }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          BARK_ENDPOINTS: ${{ secrets.BARK_ENDPOINTS }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
