name: Test

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test & Run
        env:
          CI: 1
          WEATHER_END_POINT: ${{ secrets.WEATHER_END_POINT }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          BARK_END_POINT: ${{ secrets.BARK_END_POINT }}
        run: |
          go test ./...
          go run .
